#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gnome2
version:      0.20
version_from: Gnome2.pm
installdirs:  site
requires:
    Gtk2:                          0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
